### PR TITLE
Add Sematext Docker Agent

### PR DESCRIPTION
**Pull request by megastef**
Add container and stack type templates for https://github.com/sematext/sematext-agent-docker

### CODE REVIEW

**Comment by otisg** [comment]
@deviantony any chance of merging this? TIA.

**Comment by deviantony** [comment]
@otisg I do not have access to the required tokens, can you confirm that both templates are working?

**Comment by cloudinovasi** [comment]
@otisg if we merge this, can you help us to advertise the fact?

**Comment by ncresswell** [comment]
@otisg if we merge this, can you help us to market it via social media etc?

**Comment by megastef** [comment]
@deviantony The container template works fine. You can use 
```
LOGSENE_TOKEN: 44a966f0-d898-4938-ba97-081a8f1b7fa6
SPM_TOKEN: 9519641e-82ad-4084-8daf-f391c723f9b8
```


There is an issue with testing the "stack" template. I could not find detailed docs for the stack deployment. 
 I just checked the "stack" deployment and Portainer UI shows: `open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory `

For testing I entered the following URL into portainer UI setting:  ```https://raw.githubusercontent.com/megastef/templates/master/templates.json```

I think portainer does not find the "stack" files in my git repository when I deploy the Sematext Agent Stack (Note the UI part is fine!).  Please advise how to test the "stack"file. 

```
Portainer shows an error (I used  GIT url to my template repository) 
2018/03/08 20:11:41 Starting Portainer 1.16.2 on :9000
2018/03/09 08:05:02 Starting Portainer 1.16.2 on :9000
2018/03/11 14:35:58 Starting Portainer 1.16.2 on :9000
2018/03/12 18:02:29 Starting Portainer 1.16.2 on :9000
2018/03/12 20:18:44 http error: User not found (code=404)
2018/03/14 15:22:06 http error: User not found (code=404)
2018/03/14 15:25:41 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory
 (code=500)
2018/03/14 15:25:47 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:25:51 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:25:52 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:25:53 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:26:05 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:26:09 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:26:25 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:26:40 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:26:58 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:27:15 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
2018/03/14 15:27:34 http error: open /data/compose/sematext-agent_rai9f2awrovksxn70w2124szb/stacks/sematext-agent-docker/docker-stack.yml: no such file or directory (code=400)
```

**Comment by otisg** [comment]
@ncresswell Yes, of course.

**Comment by megastef** [comment]
After last 2 commits, the stack file can be deployed with 
```
docker stack deploy -c docker-stack.yml sematext-docker-agent
```

and should work with portainer as well, right?

**Comment by deviantony** [comment]
@megastef the stack is failing because it's declared like this:

```json
    "repository": {
      "url": "https://github.com/portainer/templates",
      "stackfile": "stacks/sematext-agent-docker/docker-stack.yml"
    },
```

But the `stacks/sematext-agent-docker/docker-stack.yml` does not exists yet in this repository (PR has not been merged yet).

I'll merge and give it a try. We can still fix it after that if needed.

Thanks for the contribution ! :+1:

**Comment by deviantony** [comment]
Had to fix a small issue with the bind mounts but the stack is running:

portainer

**Comment by megastef** [comment]
@deviantony thank you very much!

**Pull request merged**
