### PR TITLE
Added Portainer Agent and Watchtower to the template

### PR DESCRIPTION
**Pull request by GolamRashed**
As the title says

### CODE REVIEW

**Comment by GolamRashed** [comment]
Added Portainer Agent and Watchtower to the template

**Comment by SvenDowideit** [comment]
@GolamRashed nice - its a shame the diff has so much formatting change in it though, its plenty hard to read :/

**Comment by GolamRashed** [comment]
@SvenDowideit That is actually weird, all I did was add the top two new templates.

**Comment by hookenz** [comment]
Thanks @GolamRashed for the PR.  Can you please remove `f17596a` from the commit, that looks like the one that makes it look like a significant change.   We usually try to keep PR's small and focused.  It's probably your editor that has gone ahead and done this.

**Comment by yi-portainer** [comment]
@SvenDowideit @hookenz please check out #147 for a new PR that removed the format changes.

**Pull request closed without merging**
