### PR TITLE
Add the Lavagna template

### PR DESCRIPTION
**Pull request by SitoCH**
Hi,
I'd like to add to the templates Lavagna, an open-source issue/project management tool designed for small teams. This is my first try so I don't know if I'm doing it correctly, mapping the template definition to the current Lavagna's Docker image is not straightforward.

Is it good or do I have to change something?

### CODE REVIEW

**Comment by deviantony** [comment]
Hi @SitoCH and thanks for the PR ! It looks good, I need to test it out. Have you tested it?

CC @ncresswell

**Comment by SitoCH** [comment]
Hi,
I tried it and I had some issues so I opted for an ad hoc image just for Portainer and updated the template.json file.
Now I can setup Lavagna in 2 easy steps using the MySQL and Lavagna templates:

- create a MySQL container with root's password "114499" and port "3306".
- create a Lavagna container, selecting as DB host the previous container, with username "root", password "114499" and port "9500".

**Comment by deviantony** [comment]
Hey @SitoCH ! After more discussion about the integration of that app we've decided to not include it in our template list. We only want apps that are really popular in our curated template list.

Thanks again for the work !

**Comment by SitoCH** [comment]
Hi, 
no problem, I really liked the idea of publishing Lavagna as a template but I understand your reasons.

Keep up the good work

**Pull request closed without merging**
