### PR TITLE
add Sematext Docker Agent

### PR DESCRIPTION
**Pull request by megastef**

### CODE REVIEW

**Comment by deviantony** [comment]
Hi @megastef 

Thanks for the PR.

We've discussed this, the main goal of our apps templates is: be really simply to deploy.

Unfortunately, this template requires the user to go to the advanced settings, choose a bind type volume and specify the path to the Docker socket on the host. We are interested in adding the sematext Docker agent as the template but we think that this is too complicated for the user so we'll figure out a way to bind mount a volume/socket in the templates.

I'll reopen your previous issue to track this evolution, closing the PR at the moment.

**Comment by megastef** [comment]
Thank you. I missed also the option to specify path on host and path in the container. In our case it is the same, so I don't mind when this option will be missing.  And a "readme" in markdown format with links would be nice, so people could just click to app-creation screen to get e.g. access tokens or find the a user manual.

**Comment by deviantony** [comment]
@megastef I like your suggestion about the readme, could you open an issue in https://github.com/portainer/portainer/issues ? We can track this one here.

**Comment by megastef** [comment]
Done: request for Readme feature https://github.com/portainer/templates/issues/67

**Pull request closed without merging**
